# Generated by Django 4.2.3 on 2023-09-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='post', to='network.comment'),
        ),
    ]
